server:
  port: 8181

spring:
  flyway:
    locations:
      - classpath:db/migration
      - classpath:db/sample_data
  datasource:
    username: postgres
    password: Kojax111
    url: jdbc:postgresql://localhost:5433/autobook

logging:
  level:
    org:
      springframework:
        security: DEBUG
