server:
  port: 8181

spring:
  datasource:
    username: postgres
    password: Kojax111
    url: jdbc:postgresql://localhost:5434/autobook

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE