server:
  port: 8181

spring:
  http:
    converters:
      preferred-json-mapper: jackson2

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE